### PR TITLE
Correct return types of RichInstant +/- operations

### PR DESCRIPTION
**Pull request by jchapuis**
Correct return types of RichInstant operations to Instant (original type)

### CODE REVIEW

**Review by johanandren — APPROVED** [review]
LGTM, thanks

**Comment by jchapuis** [comment]
cool, would it be possible to have a `1.6` release with those changes?

**Comment by johanandren** [comment]
Yup. Won't have time today but will try to get it released before the week is over!

**Comment by johanandren** [comment]
1.6 should be available from maven central shortly.

**Pull request merged**
