### PR TITLE
Add min, max and - for RichInstant

### PR DESCRIPTION
**Pull request by rgugliel**
As discussed in #23

### CODE REVIEW

**Comment by johanandren** [comment]
Looks like the travis build is broken (because of oraclejdk proprietary yadi) I'll fix that but can't do that right away, perhaps the next few days.

**Comment by rgugliel** [comment]
Ok, thanks!

**Comment by johanandren** [comment]
I've fixed the travis config in master now, please push something to trigger a new build with the fixed travis config!

**Comment by rgugliel** [comment]
I just amended last commit message and force pushed to restart the build.

**Review by johanandren — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
